# Generated by Django 4.1.7 on 2023-03-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="chore", name="kid",),
        migrations.AddField(
            model_name="parent",
            name="chores",
            field=models.ManyToManyField(to="main_app.chore"),
        ),
        migrations.AlterField(
            model_name="kid",
            name="current_balance",
            field=models.IntegerField(default=0),
        ),
    ]
