# Generated by Django 4.1.7 on 2023-03-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                ("description", models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name="chore",
            name="description",
            field=models.TextField(max_length=400),
        ),
    ]
