# Generated by Django 4.1.7 on 2023-03-12 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="kid", name="description",),
    ]
