# Generated by Django 4.1.7 on 2023-03-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kid",
            name="chores",
            field=models.ManyToManyField(to="main_app.chore"),
        ),
    ]
