# Generated by Django 4.1.7 on 2023-03-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_remove_chore_kid_parent_chores_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kid",
            name="chores",
            field=models.ManyToManyField(to="main_app.chore"),
        ),
    ]
