# Generated by Django 4.1.7 on 2023-03-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="kid",
            name="parent",
            field=models.CharField(default="jim", max_length=150),
        ),
    ]
