# Generated by Django 4.1.7 on 2023-03-08 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0004_kid_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kid",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main_app.parent"
            ),
        ),
    ]
