# Generated by Django 4.1.7 on 2023-03-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0005_alter_kid_parent"),
    ]

    operations = [
        migrations.RemoveField(model_name="chore", name="type",),
        migrations.AddField(
            model_name="chore", name="date", field=models.DateField(default="today"),
        ),
    ]
