# Generated by Django 4.1.7 on 2023-03-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0006_remove_chore_type_chore_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chore",
            name="date",
            field=models.DateField(default="2023-12-12"),
        ),
    ]
