# Generated by Django 4.1.7 on 2023-03-08 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0008_alter_chore_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chore",
            name="date",
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
