# Generated by Django 4.1.7 on 2023-03-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0009_alter_chore_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chore", name="date", field=models.DateField(blank=True),
        ),
    ]
